/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

export interface Component {
  projectId: string;
  id: string;
  name: string;
  handler: string;
  displayName: string;
  displayType: string;
  description: string;
  status: string;
  initStatus?: string;
  repository?: { organizationApp?: string; nameApp?: string };
  componentType?: string;
  componentSubType: string | null;
  version: string;
  createdAt: string;
  lastBuildDate: string;
  labels?: string | string[];
  originCloud?: string;
  apiId?: string;
  serviceAccessMode?: string | null;
  isPrebuilt?: boolean;
  /** Set while the integration's delete is accepted but its finalizers have not cleared yet. */
  deleting?: boolean;
  /** 'BI' | 'MI' | 'other' — 'other' is another platform's runtime. Cloud only. */
  buildpackType?: string;
}

export interface DeploymentTrack {
  id: string;
  autoDeployEnabled?: boolean;
  branch?: string;
  apiVersion?: string;
  description?: string;
  latest?: boolean;
  componentId?: string;
  createdAt?: string;
  updatedAt?: string;
  versionStrategy?: string;
}

export interface CreateDeploymentTrackInput {
  orgUuid: string;
  componentId: string;
  apiVersion: string;
  branch: string;
  description?: string;
}

/** Result of `deleteDeploymentTrack` (also used for proxy versions, which share the mutation). */
export interface DeleteTrackResult {
  status: string;
  canDelete: boolean;
  message: string;
  encodedData?: string;
}

/** Result of `checkDeploymentTrackDeletable`. */
export interface CheckDeletableResult {
  canDelete: boolean;
  message: string;
}

export interface ApiVersion {
  id: string;
  apiVersion: string;
  branch: string;
  latest: boolean;
  accessibility?: string;
}

export interface ComponentDetail extends Component {
  orgHandler: string;
  deploymentTracks?: DeploymentTrack[];
  apiVersions?: ApiVersion[];
}

export interface Endpoint {
  displayName: string;
  visibility: string;
  apimId?: string | null;
}

export interface EnvEndpoint {
  id: string;
  name?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  releaseId: string;
  environmentId: string;
  displayName: string;
  port?: number | null;
  type: string;
  apiContext?: string | null;
  apiDefinitionPath?: string | null;
  visibility: string;
  invokeUrl?: string | null;
  publicUrl?: string | null;
  organizationUrl?: string | null;
  projectUrl?: string | null;
  defaultPublicUrl?: string | null;
  defaultOrganizationUrl?: string | null;
  networkVisibilities?: string[] | null;
  hostName?: string | null;
  isAutoGenerated?: boolean | null;
  apimId?: string | null;
  apimRevisionId?: string | null;
  internalGwRevisionId?: string | null;
  externalGwRevisionId?: string | null;
  apimName?: string | null;
  state?: string | null;
  stateReason?: { code?: string | null; message?: string | null; details?: string | null; workerId?: string | null } | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  hasShortUrl?: boolean | null;
  shortUrlReassignState?: string | null;
  signature?: string | null;
  isScopeAdded?: boolean | null;
  generationSource?: string | null;
}

/** Input for updating an endpoint's network visibility. */
export interface UpdateEndpointInput {
  componentId: string;
  /** Cloud only — resolves the component's release bindings. wip carries the project in the id. */
  projectId?: string;
  versionId: string;
  releaseId: string;
  endpointId: string;
  displayName: string;
  /** UI labels — 'Public' | 'Organization' | 'Project'; each product maps them to its own wire values. */
  networkVisibilities: string[];
}

export interface ComponentNameAvailability {
  componentNameUnique: boolean;
  alternateComponentName: string;
}

export type DisplayType = 'ballerinaService' | 'scheduledTask' | 'manualTrigger' | 'webhook' | 'miApiService' | 'miCronjob' | 'miJob' | 'miWebhook' | 'miEventHandler' | 'ballerinaEventHandler';

export interface CreateComponentInput {
  displayName: string;
  name: string;
  description: string;
  orgHandler: string;
  projectId: string;
  displayType: DisplayType;
  /**
   * Optional subtype that further classifies the component beyond its
   * `displayType`. Used to flag File Integration (`'ballerinaFileIntegration'`,
   * `'miFileIntegration'`), AI Agent, MCP, Tailscale, etc., where the build
   * runtime is shared with another type (e.g. `ballerinaService`) but the
   * functional category differs.
   */
  componentSubType?: string;
  srcGitRepoUrl?: string;
  repositoryBranch?: string;
  repositorySubPath?: string;
  isPublicRepo?: boolean;
  secretRef?: string;
  enableAutoDeploy?: boolean;
  isPrebuilt?: boolean;
  /**
   * GitHub App installation that grants access to srcGitRepoUrl (cloud
   * private-repo mode). When set, the cloud BFF persists the source binding
   * and provisions per-build clone secrets; other variants ignore it.
   */
  gitHubAppInstallationId?: string;
}

export interface UpdateComponentInput {
  id: string;
  displayName: string;
  description: string;
  version: string;
  projectId: string;
  handler: string;
  labels?: string[];
}

export interface UpdateAutoDeployInput {
  componentId: string;
  deploymentTrackId: string;
  branch: string;
  description?: string;
  enableAutoDeploy: boolean;
}

export interface GenerateComponentEndpointsInput {
  componentId: string;
  versionId: string;
  releaseId: string;
  commitHash: string;
  dryRun?: boolean;
}

export interface DeleteComponentResult {
  status: string;
  canDelete: boolean;
  message: string;
  encodedData: string;
}

export interface SubscriptionApplicationInfo {
  applicationId: string;
  name: string;
}

export interface ComponentSubscription {
  subscriptionId: string;
  applicationInfo: SubscriptionApplicationInfo;
}

export interface SubscriptionInfo {
  count: number;
  list: ComponentSubscription[];
}

export interface ComponentDeletionError {
  code: string;
  message: string;
  data: SubscriptionInfo[];
}
