[package]
org = "wso2"
name = "icp_server"
version = "0.1.0"
license = ["Apache-2.0"]
description = "ICP Server"    

[[platform.java17.dependency]]
artifactId = "h2"
version = "2.2.224"
groupId = "com.h2database"